# Enter the paths and rename to satvis.yaml

data_directories:
  export_path: C:\EXPORT\PATH
  sub_basin_shp: C:\PATH\TO\AREAS\Havsomr_SVAR_2016_3b.shp
  # BAWS
  cyano_data_shp: C:\PATH\TO\DATA
  # ALGOTL
  sentinel2_products: C:\PATH\TO\DATA